# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['style'],
            },
        ),
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LevelingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('natDexNum', models.IntegerField()),
                ('catchRate', models.FloatField()),
                ('genderRatio', models.CharField(max_length=10)),
                ('heightUSFeet', models.IntegerField()),
                ('heightUSInches', models.IntegerField()),
                ('heightMetric', models.FloatField()),
                ('weightUS', models.FloatField()),
                ('weightMetric', models.FloatField()),
                ('hatchTimeLow', models.IntegerField()),
                ('hatchTimeHigh', models.IntegerField()),
                ('baseFriendship', models.IntegerField()),
                ('baseExpYieldUpToGen4', models.IntegerField()),
                ('baseExpYieldGen5Plus', models.IntegerField()),
                ('evHP', models.IntegerField()),
                ('evAttack', models.IntegerField()),
                ('evDefense', models.IntegerField()),
                ('evSpecialAttack', models.IntegerField()),
                ('evSpecialDefense', models.IntegerField()),
                ('evSpeed', models.IntegerField()),
                ('abilities', models.ManyToManyField(to='home.Ability')),
                ('bodyStyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BodyStyle')),
                ('eggGroup', models.ManyToManyField(to='home.EggGroup')),
                ('levelingRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LevelingRate')),
            ],
            options={
                'ordering': ['natDexNum'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionDexNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Region')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poketypes',
            field=models.ManyToManyField(to='home.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='regDexNums',
            field=models.ManyToManyField(to='home.RegionDexNum'),
        ),
    ]
