# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160714_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='egggroup',
            name='desc',
            field=models.CharField(default='Nothing written', max_length=200),
        ),
    ]
