# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_egggroup_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='effect',
            field=models.CharField(default='Nothing written', max_length=200),
        ),
        migrations.AddField(
            model_name='ability',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Generation'),
        ),
    ]
